language:
    - php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - export PHPCS_GITHUB_SRC=squizlabs/PHP_CodeSniffer
    - export PHPCS_DIR=/tmp/phpcs
    - export PHPCS_BRANCH=phpcs-fixer
    - mkdir -p $PHPCS_DIR && git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git -b $PHPCS_BRANCH $PHPCS_DIR
    - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $(pwd)

script:
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - phpunit --filter WordPress /tmp/phpcs/tests/AllTests.php
